export default [
"Sapin blanc",
"Sapin de Vancouver",
"Abutilon d'Avicenne",
"Mimosa argenté",
"Acanthe à feuilles molles",
"Erable",
"Erable de Montpellier",
"Erable negundo",
"Erable plane",
"Erable sycomore",
"Erable argenté",
"Diotis maritime",
"Achillée millefeuille",
"Sourcils-de-Vénus",
"Achillée sternutatoire",
"Acore calame",
"Adénocarpe",
"Cheveu-de-Vénus",
"Adonis annuelle",
"Adonis annuelle",
"Adoxe musquée",
"Herbe aux goutteux",
"Marronnier d'Inde",
"Petite Ciguë",
"Fausse petite Ciguë",
"Agave d'Amérique",
"Agératum du Mexique",
"Aigremoine",
"Francormier",
"Aigremoine odorante",
"Nielle des blés",
"Nielle des blés",
"Agrostide des chiens",
"Agrostide des chiens",
"Agrostide capillaire",
"Agrostis capillaire",
"Agrostide à soie",
"Agrostide géant",
"Agrostis stolonifère",
"Agrostis stolonifère à panicules diffuses",
"Agrostide des sables",
"Agrostide des sables",
"Agrostide de Murbeck",
"Ailanthe",
"Canche de Bretagne",
"Canche caryophyllée",
"Canche",
"Canche printanière",
"Bugle jaune",
"Bugle jaune",
"Bugle rampante",
"Rose trémière",
"Plantain d'eau à feuilles lancéolées",
"Plantain d'eau",
"Alliaire",
"Gros ail",
"Ail des landes",
"Ail à longue spathe",
"Ail des jardins",
"Poireau",
"Ciboulette",
"Ail à tête ronde",
"Ail à tête ronde",
"Ail un peu hérissé",
"Ail triquèdre",
"Ail des ours",
"Ail des vignes",
"Aulne cordé",
"Aulne glutineux",
"Vulpin fauve",
"Vulpin bulbeux",
"Vulpin genouillé",
"Vulpin des champs",
"Vulpin des prés",
"Vulpin des prés",
"Vulpin en outre",
"Guimauve officinale",
"Althénie d'Orient",
"Passerage champêtre",
"Amarante livide",
"Amarante Blite",
"Amarante échancrée",
"Amarante queue-de-renard",
"Amarante couchée",
"Amarante africaine",
"Amarante sylvestre",
"Amaranthe hybride",
"Amaranthe hybride",
"Amarante de Bouchon",
"Amarante réfléchie",
"Ambroisie à feuilles d'armoise",
"Ambroisie à épis lisses",
"Ambroisie trifide",
"Ammi élevé",
"Ammi élevé",
"Oyat",
"Oyat",
"Grémil à petites fleurs",
"Amsinckie velue",
"Orchis punaise",
"Orchis à fleurs lâches",
"Orchis bouffon",
"Orchis des marais",
"Orchis pyramidal",
"Orchis pyramidal",
"Orchis",
"Orchis de Lloyd",
"Buglosse officinale",
"Andryale à feuilles entières",
"Anémone des bois",
"Angélique à fruits variés",
"Angélique sauvage",
"Angélique sauvage",
"Brome à deux étamines",
"Brome de Madrid",
"Brome à deux étamines",
"Brome stérile",
"Brome des toits",
"Anogramme à frondes fines",
"Anthémis des champs",
"Anthémis des champs",
"Camomille fétide",
"Anthémis maritime",
"Flouve aristée",
"Flouve odorante",
"Cerfeuil vulgaire à fruits glabres",
"Cerfeuil cultivé",
"Persil sauvage",
"Anthyllide vulnéraire",
"Antinorie fausse-agrostide",
"Gueule de lion",
"Gueule de lion",
"Agrostis interrompu",
"Apéra Jouet-du-vent",
"Perce-pierre",
"Alchémille à petits fruits",
"",
"Céleri",
"Aponogéton odorant",
"Ancolie commune",
"Ancolie vulgaire",
"Arabette de thalius",
"Arabette des Alpes",
"Arabette hérissée",
"Arabette hérissée",
"Arbousier commun",
"Grande bardane",
"Petite bardane",
"Sabline grêle",
"Sabline des montagnes",
"Sabline des montagnes",
"Sabline à feuilles de serpolet",
"Potentille des oies",
"Canche des marais",
"Aristoloche clématite",
"Armérie des sables",
"Armérie des dunes",
"Gazon d'Olympe maritime",
"Arnoseris naine",
"Fromental élevé",
"Avoine à chapelets",
"Absinthe",
"Armoise annuelle",
"Armoise champêtre",
"Armoise de Loyd",
"Sémentine",
"Armoise maritime",
"Armoise des Frères Verlot",
"Armoise commune",
"Gouet d'Italie",
"Pied-de-veau",
"Canne de Provence",
"Asperge officinale",
"Asperge officinale",
"Asperge prostrée",
"Herbe à l'esquinancie",
"Aspérule des sables",
"Asphodèle blanc",
"Bâton royal",
"Asphodèle rameuse",
"Bâton blanc d'Arrondeau",
"Capillaire noire",
"Cétérach",
"Doradille marine",
"Doradille a feuilles ovales",
"Doradille rue des murailles",
"Rue des murailles",
"Scolopendre",
"Doradille du Nord",
"Capillaire des murailles",
"Doradille fausse-capillaire",
"Astragale à feuilles de Réglisse",
"Fougère femelle",
"Arroche de Babington",
"Arroche halime",
"Bonne dame",
"Arroche des sables",
"Arroche du littoral",
"Arroche à long pédoncule",
"Arroche étalée",
"Arroche hastée",
"Corbeille d'or",
"Avoine barbue",
"Avoine barbue",
"Folle-avoine",
"Avoine",
"Avoine à grosses graines",
"Avoine rude",
"Canche fleuxueuse",
"Avoine pubescente",
"Avoine pubescente",
"Azolla flottante",
"Séneçon en arbre",
"Baldellie fausse-renoncule",
"Baldellie rampante",
"Marrube noir",
"Ballote fétide",
"Barbarée intermédiaire",
"Barbarée du printemps",
"Barbarée commune",
"Pâquerette",
"Mahonia faux-houx",
"Berbéris commun",
"Alysson blanc",
"Berle dressée",
"Côte de bette",
"Bette-épinard",
"Bette maritime",
"Bétoine officinale",
"Bouleau verruqueux",
"Bouleau pubescent",
"Bouleau pubescent",
"Bident bipenné",
"Bident penché",
"Bident à feuilles connées",
"Bident à fruits noirs",
"Bident radié",
"Bident trifolié",
"Bident vulgaire",
"Bistorte",
"Centaurée perfoliée",
"Souchet maritime",
"Bourrache",
"Barbon Andropogon",
"Brachypode penné",
"Brachypode des bois",
"Colza",
"Moutarde noire",
"Grande brize",
"Amourette",
"Petite amourette",
"Brome érigé",
"Brome érigé",
"Brome inerme",
"Brome rude",
"Brome des champs",
"Brome variable",
"Brome mou",
"Brome mou",
"Brome de Ferron",
"Brome mou",
"Brome de Thomine",
"Brome en grappe",
"Brome faux-seigle",
"Mûrier à papier",
"Bryone dioïque",
"Buddleja du père David",
"Grémil des champs",
"Bunias d'Orient",
"Buplèvre du Mont Baldo",
"Buplèvre du Mont Baldo",
"Buplèvre en buisson",
"Buplèvre tenu",
"Buplèvre grêle",
"Butome en ombelle",
"Buis",
"Caquilier maritime",
"Caquillier à feuilles entières",
"Calamagrostide blanchâtre",
"Calamagrostide blanchâtre",
"Calamagrostide épigéios",
"Souci des champs",
"Souci officinal",
"Calépine irrégulière",
"Callitriche pédonculé",
"Callitriche à crochets",
"Callitriche à angles obtus",
"Callitriche à fruits plats",
"Callitriche des eaux stagnantes",
"Callitriche tronqué",
"Callitriche tronqué",
"Callune",
"Populage des marais",
"Campanule agglomérée",
"Campanule agglomérée",
"Campanule étalée",
"Campanule étalée",
"Campanule raiponce",
"Campanule gantelée",
"Campanule gantelée",
"Chanvre cultivée",
"Bourse-à-pasteur",
"Capselle grêle",
"Bourse-à-pasteur rougeâtre",
"Cardamine des marais",
"Cardamine des bois",
"Cardamine hirsute",
"Cardamine impatiente",
"Cardamine à petites fleurs",
"Cardamine des prés",
"Cresson des prés",
"Chardon crépu",
"Chardon penché",
"Chardon penché",
"Chardon à tête dense",
"Chardon à tête dense",
"Chardon à petits capitules",
"Laîche gracile",
"Carex des marais",
"Laîche des sables",
"Laîche à deux nervures",
"Carex printanier",
"Laiche de la Loire",
"Carex jaunâtre",
"Carex appauvri",
"Carex à épis distants",
"Laîche distique",
"Carex divisé",
"Carex tronquée",
"Carex hérissé",
"Carex élevé",
"Laîche élevée",
"Carex allongé",
"Laîche étirée",
"Langue-de-pic",
"Carex hérissé",
"Carex de Host",
"Carex lisse",
"Carex à fruits velus",
"Carex de Leers",
"Carex à fruits charmants",
"Carex à épis ovales",
"Carex à fruits lustrés",
"Laîche luisante",
"Laîche à épi noir",
"Carex noir",
"Carex cuivré",
"Carex de Paira",
"Carex pâle",
"Carex faux panic",
"Carex paniculé",
"Carex à épis pendants",
"Carex à pilules",
"Laîche à pilules",
"Carex précoce",
"Carex faux-souchet",
"Carex puce",
"Carex ponctué",
"Carex à épis espacés",
"Carex des rives",
"Carex à utricules rostrés",
"Carex en épi",
"Carex maigre",
"Carex des bois",
"Laîche des bois",
"Carex tomenteux",
"Carex vésiculeux",
"Carex tardif",
"Laîche verdâtre",
"Carex des renards",
"Carline commune",
"Caropsis de Thore",
"Charme",
"Griffe de sorcières",
"Centaurée laineuse",
"Chataignier",
"Catabrose aquatique",
"Scléropoa marin",
"Pâturin rigide",
"Micocoulier de provence",
"Pennisetum hérissé",
"Centaurée rude",
"Centaurée rude",
"Centaurée chausse-trape",
"Centaurée de Debeaux",
"Centaurée à appendice étroit",
"Centaurée des bois",
"Centaurée des prés",
"Centaurée de Debeaux",
"Centaurée jacée",
"Centaurée noire",
"Centaurée scabieuse",
"Centaurée du solstice",
"Petite centaurée commune",
"Centaurée érythrée",
"Petite centaurée maritime",
"Petite centaurée délicate",
"Petite-Centaurée délicate",
"Centaurée à fleurs étroites",
"Centranthe rouge",
"Valériane rouge",
"Céphalanthère à feuilles étroites",
"Céraiste des champs",
"Céraiste des champs",
"Céraiste à pétales courts",
"Céraiste à pétales courts",
"Céraiste à quatre étamines",
"Céraiste à quatre étamines",
"Céraiste douteux",
"Céraiste commune",
"Céraiste aggloméré",
"Céraiste nain",
"Céraiste à petites étamines",
"Céraiste à 5 étamines",
"Céraiste tomenteux",
"Corydale à vrilles",
"Brome purgatif",
"Cératophylle épineux",
"Cornifle",
"Arbre de Judée",
"Grand Mélinet",
"Petite linaire",
"Petite linaire",
"Chérophylle penché",
"Agripaume faux-marrube",
"Cyprès de Lawson",
"Camomille romaine",
"Chélidoine",
"Chénopode hybride",
"Chénopode des murs",
"Chénopode blanc",
"Senousse",
"Chénopode à feuilles de viorne",
"Vulvaire",
"Chondrille à tige de jonc",
"Dorine à feuilles opposées",
"Cicendie filiforme",
"Chicorée sauvage",
"Ciguë aquatique",
"Circée de Paris",
"Cirse acaule",
"Cirse des champs",
"Cirse Anglais",
"Cirse laineux",
"Cirse Filipendule",
"Cirse des marais",
"Cirse bulbeux",
"Cirse commun",
"Ciste à feuilles de sauge",
"Hélianthème à bouquets",
"Anthémis panaché",
"Marisque",
"Claytonie perfoliée",
"Clématite odorante",
"Clématite des haies",
"Clématite fausse-vigne",
"Calament acinos",
"Calament glanduleux",
"Calament glanduleux",
"Calament ascendent",
"Sarriette à feuilles de Menthe",
"Grand Basilic",
"Cranson d'Angleterre",
"Cranson du Danemark",
"Colchique d'automne",
"Coléanthe délicat",
"Baguenaudier",
"Comaret des marais",
"Grande Ciguë",
"Conpode dénudé",
"Muguet",
"Liseron des champs",
"Liseron des haies",
"Liseron des dunes",
"Coriandre cultivée",
"Cornouiller mâle",
"Cornouiller sanguin",
"Coronille bigarrée",
"Corrigiole des grèves",
"Corrigiole littorale",
"Herbe de la Pampa",
"Corydale solide",
"Noisetier",
"Canche des sables",
"Cotonéaster",
"Cotonéaster de Diels",
"Cotonéaster de Franchet",
"Cotonéaster horizontal",
"Cotonéaster de Simons",
"Cotule Pied-de-corbeau",
"Chou marin",
"Crassule de Helms",
"Crassule mouse",
"Crassula de Vaillant",
"Néflier",
"Aubépine lisse",
"Aubépine à un style",
"Crépide bisannuelle",
"Crépide capillaire",
"Crépide fétide",
"Crépide fétide",
"Crépide de Nîmes",
"Crépide hérissée",
"Crépis de Suffren",
"Barkhausie à feuilles de pissenlit",
"Crépide à feuilles de pissenlit",
"Perce-pierre",
"Montbrétia",
"Crocus de Naples",
"Gaillet croisette",
"Crypside piquant",
"Crypside faux vulpin",
"Cyprès de Lambert",
"Cuscute des champs",
"Cuscute du thym",
"Cuscute à petites fleurs",
"Grande cuscute",
"Cuscute volubile",
"Cuscute du Bident",
"Cuscute de Cesati",
"Bleuet",
"Cyclamen à feuilles de lierre",
"Linaire cymbalaire",
"Chiendent pied-de-poule",
"Cynoglosse officinale",
"Crète des prés",
"Crételle hérissée",
"Souchet vigoureux",
"Souchet comestible",
"Souchet brun",
"Souchet allongé",
"Souchet de Micheli",
"Fougère-houx",
"Cystopteris dickieana",
"Cystoptéris fragile",
"Cytise blanc",
"Genêt à balai",
"Cytise strié",
"Dactyle aggloméré",
"Orchis de Fuchs",
"Orchis de Fuchs",
"Orchis incarnat",
"Orchis couleur de chair",
"Dactylorhize tacheté",
"Orchis maculé",
"Dactylorhize des bruyères",
"Orchis grenouille",
"Damasonie étoilée",
"Danthonie",
"Laurier des bois",
"Daphné lauréole",
"Pomme épineuse",
"Carotte sauvage",
"Carotte de Gadeceau",
"Carotte porte gomme",
"Délosperma",
"Dauphinelle des jardins",
"Canche cespiteuse",
"Canche des champs",
"Oeillet velu",
"Oeillet velu",
"Oeillet Giroflée",
"Oeillet de France",
"Peucédan à feuille de Carvi",
"Digitale pourpre",
"Digitaire glabre",
"Digitaire sanguine",
"Herbe-aux-femmes-battues",
"Diplotaxe fausse-roquette",
"Diplotaxe des murs",
"Diplotaxe à feuilles étroites",
"Cabaret des oiseaux",
"Cardère velue",
"Inule fétide",
"Inule visqueuse",
"Doronic plantain",
"Drave des murailles",
"Drave printanière",
"Rossolis intermédiaire",
"Rossolis à feuilles rondes",
"Dryoptéris écailleux",
"Dryoptéris écailleux",
"Fougère affine",
"Fougère des chartreux",
"Dryoptéris dilaté",
"Fougère mâle",
"Dryoptéris de Deweve",
"Chénopode fausse-ambroisie",
"Chénopode à grappes",
"Chénopode couché",
"Concombre sauvage",
"Pied-de-coq",
"Panic épineux",
"Echinops à tête ronde",
"Echinops à tête ronde",
"Vipérine commune",
"Egéria",
"Olivier de bohème",
"Elatine faux-alsine",
"Elatine à six étamines",
"Elatine à gros pied",
"Scirpe épingle",
"Souchet de Buenos Aires",
"Scirpe à nombreuses tiges",
"Scirpe ovale",
"Scirpe des marais",
"Scirpe des marais",
"Souchet commun",
"Scirpe pauciflore",
"Scirpe à une écaille",
"American Yard-grass",
"Elodée à feuilles allongées",
"Elodée du Canada",
"Elodée à feuilles étroites",
"Froment des chiens",
"Chiendent du littoral",
"Chiendent des champs",
"Chiendent allongé",
"Chiendent à feuilles de Jonc",
"Chiendent à feuilles de Jonc",
"Chiendent",
"Raisin de mer",
"Ephèdre à chatons opposés",
"Epilobe en épi",
"Epilobe d'automne",
"Epilobe cilié",
"Epilobe cilié",
"Epilobe hirsute",
"Epilobe à feuilles lancéolées",
"Epilobe des montagnes",
"Epilobe vert foncé",
"Epilobe des marais",
"Epilobe à petites fleurs",
"Epilobe rosée",
"Epilobe à tige carrée",
"Epilobe de Lamy",
"Epipactis à larges feuilles",
"Epipactis des marais",
"Prêle des champs",
"Prêle des fleuves",
"Prêle des marais",
"Prêle rameuse",
"Grande prêle",
"Eragrostide de Barrelier",
"Grand erogrostis",
"Eragrostide",
"Eragrostis faux-pâturin",
"Eragrostis en peigne",
"Eragrostis poilu",
"Bruyère ciliée",
"Bruyère cendrée",
"Bruyère du Portugal",
"Bruyère à balai",
"Bruyère à balais",
"Bruyère à quatre angles",
"Bruyère vagabonde",
"Bruyère de Watson",
"Vergerette âcre",
"Vergerette annuelle",
"Vergerette d'Argentine",
"Vergerette du Canada",
"Vergerette à fleurs nombreuses",
"Vergerette de Karvinski",
"Vergerette de Sumatra",
"Linaigrette à feuilles étroites",
"Linaigrette à feuilles larges",
"Linaigrette engainée",
"Erodium d'Ethiopie",
"Bec de grue",
"Cicutaire",
"Bec-de-grue des dunes",
"Erodium de Lebel",
"Erodium à feuilles de mauve",
"Bec de grue maritime",
"Bec de Cigogne musqué",
"Roquette cultivée",
"Roquette bâtarde",
"Vesce hérissée",
"Vesce à quatre graines",
"Panicaut champêtre",
"Panicaut des dunes",
"Vélar fausse-giroflée",
"Vélar fausse-giroflée",
"Giroflée des murailles",
"Mimule tacheté",
"Pavot de Californie",
"Fusain d'Europe",
"Chanvre d'eau",
"Herbe à la faux",
"Euphorbe petit-cyprès",
"Euphorbe douce",
"Euphorbe douce",
"Euphorbe ésule",
"Euphorbe âcre",
"Euphorbe naine",
"Euphorbe réveil matin",
"Euphorbe couchée",
"Euphorbe poilue",
"Euphorbe des jardins",
"Euphorbe maculée",
"Euphorbe de Corse",
"Euphorbe maritime",
"Euphorbe péplis",
"Euphorbe peplus",
"Euphorbe à feuilles larges",
"Euphorbe prostrée",
"Euphorbe des moissons",
"Euphorbe de Portland",
"Euphorbe de Séguier",
"Euphorbe de Séguier",
"Euphorbe rampante",
"Euphorbe raide",
"Euphraise grêle",
"Euphraise des bois",
"Euphraise des montagnes",
"Cicendie fluette",
"Sarrasin",
"Hêtre",
"Renouée de Chine",
"Vrillée sauvage",
"Vrillée des buissons",
"Fétuque à feuilles rudes",
"Fétuque capillaire",
"Fétuque hétérophylle",
"Fétuque de Huon",
"Fétuque à feuilles de jonc",
"Fétuque de Léman",
"Fétuque marginée",
"Fétuque de Timbal-Lagrave",
"Fétuque noirâtre",
"Fétuque ovine",
"Fétuque traçante",
"Fétuque rouge",
"Fétuque des grèves",
"Fétuque pruineuse",
"Ficaire printanière",
"Ficaire à bulbilles",
"Ficaire",
"Figuier d'Europe",
"Immortelle des champs",
"Cotonière commune",
"Cotonnière jaunâtre",
"Cotonnière jaunissante",
"Cotonnière spatulée",
"Reine des près",
"Filipendule",
"Fenouil commun",
"Fenouil",
"Fraisier des bois",
"Bourdaine",
"Frankénie lisse",
"Frêne à feuilles aiguës",
"Frêne à feuilles aiguës",
"Frêne élevé",
"Frêne à fleurs",
"Fritillaire pintade",
"Fumeterre de Bastard",
"Fumeterre grimpante",
"Fumeterre grimpante",
"Fumeterre des murs",
"Fumeterre de Boreau",
"Fumeterre officinale",
"Fumeterre de Reuter",
"Fumeterre de Vaillant",
"Gagée de Bohème",
"Gagée de Bohème",
"Perce-neige",
"Galéga officinal",
"Galéopsis bifide",
"Galéopsis ladanum",
"Galéopsis douteux",
"Galéopsis Tétrahit",
"Galinsoga à petites fleurs",
"Galinsoga cilié",
"Gaillet dressé",
"Gratteron",
"Gaillet des sables",
"Gaillet faible",
"Gaillet allongé",
"Caillelait blanc",
"Gaillet des murs",
"Gaillet commun négligé",
"Aspérule odorante",
"Gaillet des marais",
"Gaillet de Paris",
"Gaillet du Harz",
"Gaillet aquatique",
"Caille-lait jaune",
"Gastridie",
"Gaudinie fragile",
"Genêt d'Angleterre",
"Genêt des teinturiers",
"Genêt des teinturiers",
"Genêt des teinturiers prostré",
"Gentiane pulmonaire des marais",
"Géranium colombin",
"Géranium à feuilles découpées",
"Géranium luisant",
"Géranium à feuilles molles",
"Géranium pourpre",
"Géranium fluet",
"Géranium des Pyrénées",
"Herbe à Robert",
"Géranium à feuilles rondes",
"Géranium",
"Benoîte commune",
"Glaïeul commun",
"Glaïeul d'Illyrie",
"Glaïeul d'Illyrie",
"Pavot jaune des sables",
"Chrysanthème des blés",
"Lierre terrestre",
"Févier d'Amérique",
"Glycérie dentée",
"Glycérie flottante",
"Glycérie aquatique",
"Glycérie pliée",
"Cotonnière en faux",
"Gnaphale des lieux humides",
"Gratiole officinale",
"Potamot dense",
"Gypsophile des murailles",
"Lepture cylindrique",
"Obione faux-pourpier",
"Malaxis des tourbières",
"Lierre grimpant",
"Hélianthème commun",
"Tournesol",
"Topinambour",
"Hélianthe vivace",
"Immortelle",
"Immortelle",
"Héliotrope d'Europe",
"Picride fausse-vipérine",
"Ache inondée",
"Ache",
"Berce du Caucase",
"Grande berce",
"Herniaire",
"Herniaire glabre",
"Herniaire hirsute",
"Julienne des dames",
"Julienne des dames",
"Hibiscus",
"Orchis bouc",
"Orchis géant",
"Hippocrepis à toupet",
"Faux baguenaudier",
"Argousier",
"Pesse d'eau",
"Houlque laineuse",
"Houlque molle",
"Houlque hybride",
"Pourpier de mer",
"Orge genouillée",
"Orge maritime",
"Orge sauvage",
"Orge Queue-de-rat",
"Orge des lièvres",
"Orge faux seigle",
"Mille feuille aquatique",
"Houblon",
"Jacinthe d'Espagne",
"Jacinthe des bois",
"Jacinthe",
"Hydrocharis des grenouilles",
"Hydrocotyle fausse renoncule",
"Ecuelle d'eau",
"Herbe de saint Jean",
"Jusquiame noire",
"Millepertuis Androsème",
"Millepertuis calycinal",
"Millepertuis des marais",
"Androsème fétide",
"Millepertuis velu",
"Millepertuis couché",
"Millepertuis à feuilles linéaires",
"Millepertuis maculé",
"Millepertuis perforé",
"Millepertuis élégant",
"Millepertuis à quatre ailes",
"Porcelle glabre",
"Porcelle tachetée",
"Porcelle enracinée",
"Houx commun",
"Illécèbre verticillé",
"Impatience de Balfour",
"Balsamine du Cap",
"Balsamine de l'Himalaya",
"Balsamine des bois",
"Balsamine à petites fleurs",
"Inule britannique",
"Inule conyze",
"Grande Aunée",
"Inule à feuilles de saule",
"Iris fétide",
"Iris flambe",
"Iris faux acore",
"Pastel des teinturiers",
"Isoète épineux",
"Souchet penché",
"Scirpe flottant",
"Isolépis sétacé",
"Isopyre faux-pigamon",
"Ive à feuilles de Lampourde",
"Séneçon aquatique",
"Séneçon à feuilles de barbarée",
"Jacobée maritime",
"Jacobée",
"Jasione crépue",
"Jasione des montagnes",
"Noyer noir",
"Noyer commun",
"Jonc à tépales aigus",
"Jonc aigu",
"Jonc aigu",
"Jonc articulé",
"Jonc des crapauds",
"Jonc couché",
"Jonc couché",
"Jonc capité",
"Jonc à tiges comprimées",
"Jonc aggloméré",
"Jonc diffus",
"Jonc feuillé",
"Jonc de Gérard",
"Jonc hétérophylle",
"Jonc hybride",
"Jonc glauque",
"Jonc maritime",
"Jonc nain",
"Jonc ambigu",
"Jonc à tépales obtus",
"Jonc des vasières",
"Jonc grêle",
"Genévrier commun",
"Corète",
"Velvote",
"Kickxia Elatine",
"Fausse velvote",
"Kickxia bâtarde",
"Scabieuse",
"Knautie",
"Koélérie glauque",
"Faux Ebénier",
"Pendrille",
"Laitue à feuilles de saule",
"Laitue scariole",
"Laitue toxique",
"Grand lagarosiphon",
"Lagure queue-de-lièvre",
"Ortie blanche",
"Lamier amplexicaule",
"Ortie jaune",
"Lamier Galéobdolon",
"Lamier jaune à feuilles argentées",
"Lamier des montagnes",
"Lamier hybride",
"Lamier maculé",
"Lamier pourpre",
"Gnaphale jaunâtre",
"Lampsane commune",
"Lathrée clandestine",
"Lathrée écailleuse",
"Gesse anguleuse",
"Gesse aphaca",
"Gesse hirsute",
"Pois vivace",
"Gesse à feuilles de Lin",
"Gesse de Nissole",
"Pois cultivé",
"Gesse des marais",
"Gesse de Pannonie",
"Gesse de Hongrie",
"Gesse des prés",
"Gesse à fruits ronds",
"Gesse des bois",
"Gesse tubéreuse",
"Laurier sauce",
"Faux riz",
"Miroir de Vénus hybride",
"Lentille d'eau gibbeuse",
"Petite lentille d'eau",
"Lentille d'eau minuscule",
"Lentille d'eau à trois sillons",
"Lenticule à turion",
"Liondent faux-pissenlit",
"Agripaume",
"Passerage des champs",
"Corne-de-cerf didyme",
"Passerage drave",
"Passerage à feuilles de graminée",
"Passerage hétérophylle",
"Grande Passerage",
"Passerage des décombres",
"Cresson alénois",
"Corne-de-cerf écailleuse",
"Passerage de Virginie",
"Marguerite",
"Grande-Marguerite",
"Nivéole d'été",
"Elyme des sables",
"Troène du Japon",
"Troëne",
"Inule faux crithme",
"Statice à feuilles de Lychnis",
"Statice de Salmon",
"Statice de Dodart",
"Statice à feuilles ovales",
"Saladelle",
"Limoselle",
"Linaire des sables",
"Linaire de Pélissier",
"Linaire rampante",
"Linaire couchée",
"Linaire commune",
"Linaire des haies",
"Lindernie fausse-gratiole",
"Lin purgatif",
"Lin de France",
"Lin cultivé",
"Lin cultivé",
"Lin bisannuel",
"Chénopode à nombreuses graines",
"Liquidambar",
"Grémil officinal",
"Littorelle à une fleur",
"Lobélie brulante",
"Lobulaire maritime",
"Cotonnière de France",
"Cotonnière naine",
"Fétuque Roseau",
"Fétuque géante",
"Ray-gras d'Italie",
"Ray-grass",
"Fétuque des prés",
"Ray-grass hybride",
"Hybrid Fescue",
"Aspergette",
"Chèvrefeuille du Japon",
"Chèvrefeuille",
"Chèvrefeuille des bois",
"Lotier à feuilles étroites",
"Lotier corniculé",
"Lotier à feuilles ténues",
"Dorycnium hérissé",
"Lotier velu",
"Lotier à petites fleurs",
"Lotus des marais",
"Jussie",
"Ludwigie des marais",
"Jussie",
"Monnaie du Pape",
"Lupin réticulé",
"Lupin réticulé",
"Flûteau nageant",
"Luzule champêtre",
"Luzule à inflorescences denses",
"Luzule de Forster",
"Luzule à nombreuses fleurs",
"Luzule de printemps",
"Luzule des bois",
"Luzule des bois",
"Coquelourde",
"Lychnis fleur de coucou",
"Lyciet commun",
"Lyciet de Chine",
"Lycopode des tourbières",
"Lycopside des champs",
"Lycope d'Europe",
"Mouron rouge",
"Morgeline",
"Mouron bleu",
"Astérolinon",
"Herbe au lait",
"Centenille",
"Lysimaque des bois",
"Herbe aux écus",
"Lysimaque ponctuée",
"Mouron délicat",
"Lysimaque commune",
"Péplis dressé",
"Salicaire à feuilles d'hysope",
"Pourpier d'eau",
"Salicaire",
"Pommier cultivé",
"Pommier sauvage",
"Mauve alcée",
"Mauve royale",
"Mauve musquée",
"Lavatère de Crète",
"Petite Mauve",
"Mauve de Nice",
"Mauve à petites fleurs",
"Guimauve hérissée",
"Grande Mauve",
"Marrube blanc",
"Marsilea à quatre feuilles",
"Matricaire camomille",
"Matricaire discoide",
"Fougère à plumes d'autruche",
"Violier",
"Violier",
"Matthiole sinuata",
"Luzerne d'Arabie",
"Luzerne sombre",
"Luzerne striée",
"Luzerne du littoral",
"Lupuline",
"Luzerne marine",
"Luzerne naine",
"Luzerne polymorphe",
"Luzerne rigide",
"Luzerne commune",
"Luzerne cultivée",
"Luzerne à gousses en faux",
"Mélampyre des prés",
"Mélique ciliée",
"Mélique ciliée",
"Mélique uniflore",
"Mélisse",
"Mélisse officinale",
"Mélitte à feuilles de Mélisse",
"Mélitte à feuilles de Mélisse",
"Menthe aquatique",
"Menthe des champs",
"Menthe à longues feuilles",
"Menthe à longues feuilles",
"Pouliot",
"Menthe en épi",
"Menthe à feuilles rondes",
"Menthe verticillée",
"Trèfle d'eau",
"Mercuriale annuelle",
"Mercuriale vivace",
"Mibora naine",
"Catapode des graviers",
"Millet diffus",
"Alsine à feuilles étroites",
"Minuartie à feuilles étroites",
"Minuartie méditerranéenne",
"Belle de nuit",
"Roseau chinois",
"Tête-de-mort",
"Moehringie trinervée",
"Moenchie",
"Moenchie",
"Molinie bleue",
"Green Carpetweed",
"Monotrope sucepin",
"Monotrope Sucepin",
"Monotrope du Hêtre",
"Montie naine",
"Mouron des fontaines",
"Montie du Portugal",
"Muscari botryoïde",
"Muscari en grappe",
"Muscari de Lelièvre",
"Muscari à toupet",
"Muscari négligé",
"Myosotis des champs",
"Myosotis de deux couleurs",
"Myosotis lâche",
"Myosotis cespiteux",
"Myosotis rameux",
"Myosotis de Lebel",
"Myosotis des marais",
"Myosotis rampant",
"Myosotis des marais",
"Myosotis des forêts",
"Myosoton aquatique",
"Queue de souris",
"Piment royal",
"Myriophylle à feuilles alternes",
"Myriophylle aquatique",
"Myriophylle en épi",
"Myriophylle verticillé",
"Grande naïade",
"Petite naïade",
"Trompette de Méduse",
"Trompette de Méduse",
"Petite narcisse",
"Jonquille des bois",
"Jonquille",
"Grande Jonquille",
"Narcisse-bouquet",
"Nard raide",
"Ossifrage ou brise-os",
"Cresson à petites feuilles",
"Cresson de fontaine",
"Orchis brûlé",
"Neottie nid-d'oiseau",
"Listère à feuilles ovales",
"Herbe aux chats",
"Nicandre faux-coqueret",
"Nigelle de Damas",
"Tabouret perfolié",
"Nénuphar jaune",
"Nénuphar blanc",
"Faux nénuphar",
"Odontite rouge",
"Odontite rouge",
"Odontitès tardif",
"Oenanthe aquatique",
"Pensacre",
"Oenanthe fistuleuse",
"Oenanthe de Foucaud",
"Oenanthe de Lachenal",
"Oenanthe à feuilles de peucédan",
"Oenanthe faux boucage",
"OEnanthe intermédiaire",
"Herbe aux unes",
"Onagre trompeuse",
"Onagre à sépales rouges",
"Gaura de Lindheimer",
"Onagre d'Oehlkers",
"Onagre dressée",
"Onagre parfumé",
"Scille du Pérou",
"Sainfoin",
"Bugrane épineuse",
"Arrête-boeuf",
"Onopordon faux-acanthe",
"Chardon aux ânes",
"Ophioglosse des Açores",
"Ophioglosse commun",
"Ophrys Abeille",
"Ophrys araignée",
"Ophrys mouche",
"Ophrys de la Passion",
"Orchis homme pendu",
"Orchis mâle",
"Orchis mâle",
"Fougère des montagnes",
"Origan commun",
"Orlaya à grandes fleurs",
"Dame-d'onze-heures",
"Dame d'onze heures",
"Ornithope comprimé",
"Ornithope délicat",
"Ornithope penné",
"Orobanche violette",
"Orobanche giroflée",
"Orobanche du lierre",
"Petite Orobanche",
"Orobanche de la picride",
"Orobanche du Genêt",
"Osmonde royale",
"Pain de coucou",
"Oxalis articulé",
"Oxalis articulé",
"Oxalis corniculé",
"Oxalis en corymbe",
"Oxalis en corymbe",
"Oxalis dressé",
"Oxalis à larges feuilles",
"Oxalide droit",
"Chénopode à feuilles grasses",
"Chénopode glauque",
"Chénopode rouge",
"Chénopode des villages",
"Lys de mer",
"",
"Panic capillaire",
"Panic à fleurs dichotomes",
"Panic de Hillmann",
"Millet commun",
"Coquelicot Argémone",
"Coquelicot douteux",
"Pavot faux glaux",
"Pavot hybride",
"Coquelicot",
"Pavot",
"Lepture courbé",
"Lepture raide",
"Parentucelle à larges feuilles",
"Bartsie visqueuse",
"Pariétaire des murs",
"Paronyque argentée",
"Vigne-vierge commune",
"Paspale dilaté",
"Paspale à deux épis",
"",
"Paspale",
"Panais cultivé",
"Panais brûlant",
"Paulownia",
"Tartarie rouge",
"Pédiculaire des marais",
"Pédiculaire des forêts",
"Pédiculaire des forêts",
"Buglosse toujours vert",
"Bourreau-des-arbres",
"Renouée amphibie",
"Poivre d'eau",
"Renouée à feuilles de Patience",
"Renouée gonflée",
"Renouée du Danube",
"Persicaire",
"Petite Renouée",
"Renouée douce",
"Renouée orientale",
"Pétasite hybride",
"Pétasite odorant",
"Oeillet de Nanteuil",
"Oeillet prolifère",
"Oeillet saxifrage",
"Persil",
"Peucédan de France",
"Fenouil de porc",
"Fenouil de porc",
"Phacélie à feuilles de Tanaisie",
"Fromenteau",
"Alpiste",
"Petit Alpiste",
"Orpin bâtard",
"Orobanche pourprée",
"Fléole des sables",
"Fléole noueuse",
"Fléole de Boehmer",
"Fléole des prés",
"Roseau",
"Alkèkenge",
"Coqueret du Pérou",
"Raiponce en épi",
"Raisin d'Amérique",
"Epicéa commun",
"Epicéa de Sitka",
"Picride fausse-éperviaire",
"Piloselle orange",
"Epervière orangée",
"Piloselle petite-laitue",
"Piloselle",
"Boulettes d'eau",
"Grand boucage",
"Grand Boucage",
"Petit boucage",
"Grassette du Portugal",
"Pin noir d'Autriche",
"Pin Laricio",
"Pin maritime",
"Pin pignon",
"Pin de Monterey",
"Pin Weymouth",
"Pin silvestre",
"Laitue d'eau",
"Plantain des sables",
"Plantain Corne-de-cerf",
"Plantain caréné",
"Plantain lancéolé",
"Grand plantain",
"Plantain intermédiaire",
"Plantain maritime",
"Platanthère à deux feuilles",
"Platanthère à fleurs verdâtres",
"Platane d'Espagne",
"Pâturin annuel",
"Pâturin bulbeux",
"Pâturin bulbeux",
"Pâturin comprimé",
"Pâturin grêle",
"Pâturin des bois",
"Pâturin des marais",
"Pâturin des prés",
"Pâturin des prés",
"Pâturin à feuilles étroites",
"Gazon d'Angleterre",
"Polycarpon à quatre feuilles",
"Polygala à feuilles de serpollet",
"Polygala commun",
"Polygala vulgaire",
"Sceau de Salomon multiflore",
"Renouée des oiseaux",
"Renouée littorale",
"Renouée des champs",
"Renouée maritime",
"Polypode austral",
"Polypode intermédiaire",
"Polypode commun",
"Polypode",
"Polypode",
"Polypogon maritime",
"Polypogon de Montpellier",
"Polypogon vrai",
"Polystic à aiguillon",
"Polystic sétacé",
"Polystic de Bicknell",
"Peuplier blanc",
"Peuplier noir",
"Peuplier à feuilles de Bouleau",
"Tremble",
"Peuplier du Canada",
"Peuplier grisard",
"Pourpier",
"Pourpier maraîcher",
"Potamot à feuilles aiguës",
"Potamot de Berchtold",
"Potamot coloré",
"Potamot à feuilles crépues",
"Potamot à feuilles mucronées",
"Potamot graminée",
"Potamot à feuilles luisantes",
"Potamot nageant",
"Potamot noueux",
"Potamot à feuilles obtuses",
"Potamot à feuilles perfoliées",
"Potamot à feuilles de renouée",
"Potamot fluet",
"Potamot filiforme",
"Potamot de Ziz",
"Potentille d'Angleterre",
"Potentille tormentille",
"Fraisier d'Inde",
"Potentille des montagnes",
"Potentille négligée",
"Potentille norvégienne",
"Potentille dressée",
"Quintefeuille",
"Potentille faux fraisier",
"Potentille printanière",
"Potentille mixte",
"Petite Pimprenelle",
"Petite Pimprenelle",
"Pimprenelle muriquée",
"Brérelle",
"Primevère acaule",
"Primevère variable",
"Scille d'automne",
"Brunelle laciniée",
"Brunelle commune",
"Brunelle intermédiaire",
"Merisier",
"Prunier myrobolan",
"Griottier",
"Prunier domestique",
"Laurier-cerise",
"Laurier de Portugal",
"Cerisier à grappes",
"Cerisier à grappes",
"Pêcher",
"Cerisier tardif",
"Prunellier",
"Prunellier à gros fruits",
"Corydale jaunâtre",
"Corydale jaunâtre",
"Corydale jaune",
"Cotonnière ondulée",
"Atropis couché",
"Sapin de Douglas",
"Fougère aigle",
"Noyer du Caucase",
"Atropis distant",
"Atropis distant",
"Atropis fasciculé",
"Atropis fasciculé",
"Puccinellie de Foucaud",
"Glycérie maritime",
"Pulicaire dysentérique",
"Pulicaire commune",
"Pulmonaire à feuilles longues",
"Buisson ardent",
"Pyrole à feuilles rondes",
"Pirole à feuilles rondes",
"Poirier sauvage",
"Poirier sauvage",
"Poirasse",
"Chêne chevelu",
"Chêne vert",
"Chêne des marais",
"Chêne sessile",
"Chêne pubescent",
"Chêne tauzin",
"Chêne pédoncule",
"Chêne rouge d'Amérique",
"Radiole",
"Bouton d'or",
"Pied-de-coq",
"Renoncule aquatique",
"Renoncule des champs",
"Renoncule à tête d'or",
"Renoncule bulbeuse",
"Renoncule divariquée",
"Petite Douve",
"Renoncule à feuilles de lierre",
"Grande Douve",
"Renoncule nodiflore",
"Renoncule toute blanche",
"Renoncule de Lenormand",
"Renoncule à feuilles d'ophioglosse",
"Renoncule des marais",
"Renoncule à petites fleurs",
"Renoncule peltée",
"Renoncule peltée",
"Renoncule de Baudot",
"Renoncule à pinceau",
"Renoncule à pinceau",
"Renoncule rampante",
"Renoncule des mares",
"Renoncule scélérate",
"Renoncule serpent",
"Renoncule à feuilles capillaires",
"Renoncule de Drouet",
"Renoncule à feuilles capillaires",
"Renoncule tripartite",
"Renoncule des bois",
"Ravenette",
"Radis sauvage",
"Radis maritime",
"Radis",
"Rapistre rugueux",
"Rapistre d'Orient",
"Réséda blanc",
"Réséda jaune",
"Gaude",
"Réséda raiponce",
"Renouée du Japon",
"Renouée de Bohême",
"Alaterne",
"Nerprun purgatif",
"Rhinanthe velu",
"Rhinanthe à grandes fleurs",
"Rhinanthe à grandes fleurs",
"Petit cocriste",
"Rhododendron des parcs",
"Sumac hérissé",
"Rhynchospore blanc",
"Rhynchospore brune",
"Cassis",
"Groseillier à grappes",
"Groseillier à maquereau",
"Ricin",
"Robinier faux-acacia",
"Romulée à petites fleurs",
"Romulée à petites fleurs",
"Romulée à petites fleurs",
"Rorippe amphibie",
"Rorippe faux-cresson",
"Rorippe des Pyrénées",
"Rorippe des forêts",
"Rosier des haies",
"Rosier des champs",
"Short-pedicelled Rose",
"Rosier à petites fleurs",
"Rosier rugueux",
"Rosier de tous les mois",
"Rosier pimprenelle",
"Rose stylée",
"Rosier tomenteux",
"Fausse fléole",
"Garance voyageuse",
"Ronce",
"Ronce",
"Rosier bleue",
"Ronce des haies",
"Framboisier",
"Ronce à grandes feuilles",
"Ronce",
"Ronce de Muenter",
"Ronce",
"Ronce à fleurs blanches",
"Ronce des bois",
"Ronce sillonnée",
"Rosier à feuilles d'orme",
"Ronce revêtue",
"Ronce",
"Oseille",
"Petite oseille",
"Petite Oseille des Pyrénées",
"Parelle",
"Parelle",
"Patience aquatique",
"Patience maritime",
"Patience sauvage",
"Patience des marais",
"Patience-violon",
"Rumex joli",
"Patience des rochers",
"Patience sanguine",
"Oseille à oreillettes",
"Oseille des champs",
"Ruppie maritime",
"Ruppie spiralée",
"Houx fragon",
"Sagine apétale",
"Sagine sans pétales",
"Sagine dressée",
"Sagine maritime",
"Sagine couchée",
"Sagine couchée",
"Sagine subulée",
"Sagittaire à larges feuilles",
"Flèche-d'eau",
"Salicorne",
"Salicorne de Lorraine",
"Salicorne de Lorraine",
"Salicorne d'Europe",
"Salicorne naine",
"Salicorne sombre",
"Salicorne couchée",
"Salicorne fragile",
"Saule blanc",
"Saule à feuilles d'Olivier",
"Saule à oreillettes",
"Marsau",
"Saule cendré",
"Osier rouge",
"Saule rampant",
"Saule rampant",
"Saule rampant",
"Saule à trois étamines",
"Osier brun",
"Osier blanc",
"Saule",
"Osier jaune",
"Saule fragile",
"Muguet des pampas",
"Soude brûlée",
"Sauge officinale",
"Sauge des prés",
"Sclarée",
"Sauge fausse-verveine",
"Yèble",
"Sureau noir",
"Samole de Valerand",
"Sanguisorbe officinale",
"Sanicle d'Europe",
"Saponaire",
"Salicorne en buisson",
"Salicorne vivace",
"Salicorne vivace",
"Saxifrage granulée",
"Saxifrage à trois doigts",
"scabieuse maritime",
"Scabieuse Colombaire",
"Peigne de Vénus",
"Scandix Peigne-de-Vénus",
"Souchet des lacs",
"Scirpe piquant",
"Jonc des chaisiers glauque",
"Scirpe triquètre",
"Schoin noirâtre",
"Souchet holoschoenus",
"Scirpe des bois",
"Scléranthe annuelle",
"Gnavelle annuelle",
"Scléranthe vivace",
"Scléranthe vivace",
"Scolyme d'Espagne",
"Petite scorsomère",
"Liondent d'automne",
"Scrofulaire aquatique",
"Scrophulaire noueuse",
"Scrofulaire à feuilles de germandrée",
"Scutellaire à casque",
"Scutellaire à feuilles hastées",
"Scutellaire naine",
"Orpin âcre",
"Orpin blanc",
"Vermiculaire d'Angers",
"Orpin anglais",
"Sédum rougeâtre",
"Orpin paniculé",
"Orpin à pétales dressés",
"Orpin rouge",
"Orpin réfléchi",
"Orpin de Nice",
"Orpin à six angles",
"Orpin velu",
"Sélaginelle des jardiniers",
"Joubarbe des toits",
"Séneçon sud-africain",
"Séneçon des bois",
"Séneçon visqueux",
"Séneçon commun",
"Sénéçon commun des dunes",
"Sérapias à petites fleurs",
"Sarrette des teinturiers",
"Serratule des teinturiers",
"Serratule des tinturiers sous-espèce de Seoane",
"Faux sésame",
"Sésélie annuelle",
"Sésélie annuelle",
"Séséli des montagnes",
"Séséli des montagnes",
"Sétaire",
"Sétaire verte",
"Sétaire glauque",
"Sétaire verticillée",
"Shérardie des champs",
"Sibthorpia d'Europe",
"Silaüs des prés",
"Cucubale à baies",
"Silène conique",
"Compagnon rouge",
"Silène de France",
"Compagnon blanc",
"Silène penché",
"Silène penché",
"Silène à oreillettes",
"Silène des ports",
"Silène maritime",
"Silène enflé",
"Silène vulgaire",
"Chardon-Marie",
"Simethis à feuilles aplaties",
"Moutarde blanche",
"Moutarde blanche",
"Moutarde des champs",
"Sison amome",
"Berle des blés",
"Sisymbre fausse moutarde",
"Herbe aux chantres",
"Sisymbre d'Orient",
"",
"Berle à larges feuilles",
"Maceron",
"Soude commune",
"Morelle faux chénopode",
"Douce-amère",
"Tomate",
"Morelle noire",
"Morelle noire",
"Morelle de Schultes",
"Morelle à feuilles de coqueret",
"Morelle",
"Morelle fausse Saracha",
"Morelle",
"Morelle poilue",
"Morelle ailée",
"Soleirole de Soleirol",
"Solidage du Canada",
"Solidage géante",
"Verge-d'or",
"Verge d'or",
"Laiteron des champs",
"Laiteron des champs",
"Laiteron épineux",
"Crépis bulbeux",
"Crépis bulbeux",
"Laiteron maritime",
"Laiteron potager",
"Sorbier des oiseleurs",
"Sorbier",
"Alisier torminal",
"Herbe de Cuba",
"Rubanier émergé",
"Rubanier dressé",
"Ruban-d'eau",
"Rubanier négligé",
"Rubanier nain",
"Spartine anglaise",
"Spartine maritime",
"Spartine de Townsend",
"Genêt d'Espagne",
"Spergule des champs",
"Spergule des champs",
"Spergulaire de Boccone",
"Spergulaire à graine hérissée",
"Spergulaire du sel",
"Spergulaire marginée",
"Spargoute printanière",
"Spergule à cinq étamine",
"Spergulaire rouge",
"Spergulaire des rochers",
"Sphénope",
"Spiranthe d'été",
"Spiranthe d'automne",
"Lentille d'eau à plusieurs racines",
"Sporobole fertile",
"Epiaire annuelle",
"Epiaire des champs",
"Epiaire d'Allemagne",
"Epiaire d'Allemagne",
"Epiaire des marais",
"Epiaire droite",
"Epiaire des bois",
"Stellaire des marais",
"Stellaire à feuilles de graminées",
"Stellaire holostée",
"Mouron des oiseaux",
"Stellaire négligée",
"Stellaire pâle",
"Stellaire des marais",
"Sténotaphrum",
"Vendangeuse",
"Faux aloès",
"Blechnum en épi",
"Potamot pectiné",
"Suéda maritime",
"Suéda maritime",
"Soude vraie",
"Succise des prés",
"Symphorine à fruits blancs",
"Aster lancéolé",
"Aster de virginie",
"",
"Aster écailleux",
"Aster à feuilles de Saule",
"Consoude à bulbe",
"Grande consoude",
"Lilas",
"Tamaris commun",
"Grande-Camomille",
"Tanaisie commune",
"Pissenlit d'Angleterre",
"Dent de lion",
"Pissenlit à fruits rouges",
"Cyprès chauve",
"If à baies",
"Téesdalie à tige nue",
"Epinard de Nouvelle-Zélande",
"Germandrée des marais",
"Germandrée des marais",
"Germandrée des marais",
"Germandrée scorodoine",
"Pigamon jaune",
"Fougère des marais",
"Thésium couché",
"Tabouret alliacé",
"Tabouret des champs",
"Thym précoce",
"Serpolet à poils variables",
"Thym précoce",
"Thym faux pouliot",
"Thym serpolet",
"Thym",
"Peucédan à feuilles en lanières",
"Peucédan des marais",
"Tilleul à petites feuilles",
"Tilleul à grandes feuilles",
"Tilleul à grandes feuilles",
"Tilleul commun",
"Trépane barbue",
"Tordyle majeur",
"Torilis pourpre",
"Torilis des champs",
"Torilis des champs",
"Torilis du Japon",
"Torilis noueux",
"Torilis noueuse",
"Torilis de Webb",
"Palmier de Chusan",
"Salcifis douteux",
"Salsifis pâle",
"Salsifis blanc",
"Salsifis à feuilles de poireau",
"Salsifis à feuilles de poireau",
"Salsifis des prés",
"Salsifis des prés",
"Petit Salsifis",
"Bardanette en grappe",
"Châtaigne d'eau",
"Croix-de-Malte",
"Trèfle",
"Trèfle à folioles étroites",
"Pied-de-lièvre",
"Pied-de-lièvre",
"Trèfle de Boccone",
"Trèfle des champs",
"Trèfle douteux",
"Trèfle fraise",
"Trèfle aggloméré",
"Trèfle hérissé",
"Trèfle hybride",
"Trèfle incarnat",
"Trèfle intermédiare",
"Trèfle intermédiare",
"Trèfle de Micheli",
"Trèfle à petites fleurs",
"Trèfle noircissant",
"Trèfle noircissant",
"Trèfle jaunâtre",
"Trèfle pied d'oiseau",
"Trèfle étalé",
"Trèfle des prés",
"Trèfle violet",
"Trèfle rampant",
"Trèfle renversé",
"Trèfle scabre",
"Trèfle maritime",
"Trèfle raboteux",
"Trèfle strié",
"Trèfle raide",
"Trèfle souterrain",
"Trèfle étranglé",
"Trèfle cotonneux",
"Troscart maritime",
"Troscart des marais",
"Mélilot blanc",
"Mélilot élevé",
"Mélilot officinal",
"Mélilot des Indes",
"Matricaire inodore",
"Matricaire maritime",
"Aster de Hongrie",
"Aster maritime",
"Avoine dorée",
"Blé commun",
"Carvi verticillé",
"Hélianthème taché",
"Tulipe de Gaule",
"Tulipe sauvage",
"Tourette glabre",
"Tussilage",
"Massette à feuilles étroites",
"Massette à larges feuilles",
"Massette glauque",
"Ajonc d'Europe",
"Landier",
"Ajonc de Le Gall",
"Ajonc nain",
"Orme blanc",
"Orme lisse",
"Petit orme",
"Grand orme",
"Ombilic de Vénus",
"Ortie dioique",
"Ortie à membranes",
"Petite Ortie",
"Utriculaire citrine",
"Utriculaire intermédiaire",
"Utriculaire mineure",
"Utriculaire commune",
"Myrtille",
"Canneberge à gros fruits",
"Valériane dioïque",
"Valériane dioïque",
"Valériane officinale",
"Valériane officinale",
"Mâche dentée",
"Mâche à oreillettes",
"Mâche potagère",
"Valérianelle carénée",
"Vallisnérie",
"Trichomanès remarquable",
"Molène blattaire",
"Molène faux-bouillon-blanc",
"Molène Lychnitis",
"Molène noire",
"Molène noire",
"Bouillon blanc",
"Bouillon blanc",
"Molène sinuée",
"Bouillon blanc",
"Molène fausse-blattaire",
"Verveine de Bueno aires",
"Verveine officinale",
"Véronique à feuilles d'acinos",
"Véronique agreste",
"Véronique Mouron d'eau",
"Véronique faux Mouron",
"Véronique des champs",
"Cresson de cheval",
"Véronique aquatique",
"Véronique petit chêne",
"Véronique cymbalaire",
"Véronique filiforme",
"Véronique à feuilles de lierre",
"Véronique des montagnes",
"Thé d'Europe",
"Véronique voyageuse",
"Véronique de Perse",
"Véronique luisante",
"Véronique à écusson",
"Véronique à feuilles de Serpolet",
"Véronique à feuilles presque lobées",
"Viorne lantane",
"Viorne obier",
"Laurier-Tin",
"Vesce à feuilles étroites",
"Vesce de Bithynie",
"Vesce cracca",
"Vesce à gousses velues",
"Vesce printannière",
"Lentille",
"Vesce jaune",
"Vesce jaune",
"Vesce cultivée",
"Poisette",
"Vesce des moissons",
"Vesce des haies",
"Vesce velue",
"Grande pervenche",
"Petite pervenche",
"Dompte-venin",
"Dompte-venin",
"Pensée des champs",
"Violette des chiens",
"Violette hérissée",
"Pensée de Kitaibel",
"Violette blanc de lait",
"Violette odorante",
"Violette sauvage",
"Violette de Rivinus",
"Violette suave",
"Pensée",
"Pensée tricolore",
"Violette intermédiaire",
"Gui commun",
"Vigne",
"Vigne cultivée",
"Vulpie faux Brome",
"Vulpie ambiguë",
"Vulpie ciliée",
"Vulpie ambiguë",
"Vulpie à une seule glume",
"Vulpie à une seule glume",
"Vulpie Queue-de-souris",
"Campanille à feuilles de lierre",
"Lentille d'eau sans racine",
"Polypogon du littoral",
"Lampourde à gros fruits",
"Lampourde à gros fruits",
"Lampourde d'Italie",
"Lampourde épineuse",
"Lampourde Glouteron",
"Yucca",
"Yucca",
"Zannichellie à feuilles obtuses",
"Zannichellie des marais",
"Zannichellie des marais",
"Zannichellie pédicellée",
"Zostère marine",
"Zostère de Nolte",
]
